version: "3.8"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

  django_app:
    build: .
    command: python Django_project/manage.py runserver 0.0.0.0:5000
    ports:
      - 5000:5000
    env_file: .env
    depends_on:
#      - nginx_app
      - db
volumes:
  postgres_data: